
CREATE TABLE metiers
(
  idMetier NUMBER(4,0) NOT NULL PRIMARY KEY,
  metier VARCHAR2(32) NOT NULL,
  salaire NUMBER(6,2) NOT NULL
);

CREATE TABLE typeJournal
(
  idType NUMBER(4,0) NOT NULL PRIMARY KEY,
  nomType VARCHAR2(32) NOT NULL
);

CREATE TABLE personnes
(
  idPers VARCHAR2(8) NOT NULL PRIMARY KEY,
  nomPers VARCHAR2(80) NOT NULL,
  prenom VARCHAR2(80) NOT NULL,
  numTel NUMBER(12,0) NOT NULL,
  idMetier NUMBER(4) NOT NULL,
  CONSTRAINT CSTR_ID_METIER_PERSONNE
  FOREIGN KEY ( idMetier ) REFERENCES metiers(idMetier)
);

CREATE TABLE ARTICLES
(
  IDARTICLES NUMBER(8,0) NOT NULL PRIMARY KEY,
  DATEREDAC DATE NOT NULL,
  TITREARTICLE VARCHAR2(100) NOT NULL,
  RESUMEARICLE VARCHAR2(2000)
);

CREATE TABLE CONTENUS
(
  IDCONTENU NUMBER(10,0) NOT NULL PRIMARY KEY,
  /* Taille max des URLs sur internet */
  URL VARCHAR2(2083) NOT NULL,
  TITRECONT VARCHAR2(100) NOT NULL,
  TYPECONTENU VARCHAR2(50) NOT NULL,
  AUTHEUR VARCHAR2(8) NOT NULL,
  CONSTRAINT AUTHEUR_CONTENUS
  FOREIGN KEY (AUTHEUR) REFRENCES PERSONNES.IDPERS
);

CREATE TABLE NUMEROS
(
  IDJOURNAL NUMBER(8,0) NOT NULL PRIMARY KEY,
  IDUNE NUMBER(8,0) NOT NULL,
  NBTIRAGE NUMBER(10,0),
  PRIX NUMBER(6,2),
  REDACCHEF VARCHAR2(8) NOT NULL,
  IDTYPE NUMBER(4,0) NOT NULL,
  DATEPARU DATE,
  CONSTRAINTS FK_NUMEROS
    FOREIGN KEY (REDACCHEF) REFERENCES PERSONNES.IDPERS,
    FOREIGN KEY (IDTYPE) REFERENCES TYPESJOURNAL.IDTYPE
);
